unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-u

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -n M-[ previous-window
bind-key -n M-] next-window

setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'

set-option -g status-position bottom

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor" 

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# tmux-power theme
set -g @plugin 'wfxr/tmux-power'

# set -g @tmux_power_theme 'snow'
# set -g @tmux_power_theme '#16a085' 
set -g @tmux_power_theme '#4d9280'
#'#89c0d0'
set -g @tmux_power_prefix_highlight_pos 'R'
set -g @tmux_power_right_arrow_icon     ''
set -g @tmux_power_left_arrow_icon      ''

# nvim escape delay
set -sg escape-time 0

# Ensure new panes retain the current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Optional: Also set new windows to use the current path
bind c new-window -c "#{pane_current_path}"

# Tmux keybinding to create and delete sessions
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
